# Generated by Django 5.1.3 on 2024-11-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'championship',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('penalty1', models.IntegerField()),
                ('penalty2', models.IntegerField()),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='ClubStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('wins', models.IntegerField(blank=True)),
                ('losses', models.IntegerField(blank=True)),
                ('draws', models.IntegerField(blank=True)),
                ('goals_for', models.IntegerField(blank=True)),
                ('goals_against', models.IntegerField(blank=True)),
                ('yellow_cards', models.IntegerField(blank=True)),
                ('red_cards', models.IntegerField(blank=True)),
                ('walkover', models.IntegerField(blank=True)),
                ('id_championship', models.ForeignKey(db_column='id_championship', on_delete=django.db.models.deletion.DO_NOTHING, related_name='club_statistics', to='core.championship')),
                ('id_club', models.ForeignKey(db_column='id_club', on_delete=django.db.models.deletion.DO_NOTHING, related_name='club_statistics', to='core.club')),
            ],
            options={
                'db_table': 'club_statistics',
            },
        ),
        migrations.CreateModel(
            name='MatchClub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('goals', models.IntegerField(blank=True)),
                ('id_club', models.ForeignKey(db_column='id_club', on_delete=django.db.models.deletion.DO_NOTHING, related_name='club_matches', to='core.club')),
                ('id_match', models.ForeignKey(db_column='id_match', on_delete=django.db.models.deletion.DO_NOTHING, related_name='club_matches', to='core.matches')),
            ],
            options={
                'db_table': 'club_matches',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('yellow_cards', models.IntegerField(blank=True, null=True)),
                ('red_cards', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(blank=True)),
                ('shirt_number', models.IntegerField(blank=True)),
                ('id_championship', models.ForeignKey(db_column='id_championship', on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_statistics', to='core.championship')),
                ('id_player', models.ForeignKey(db_column='id_player', on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_statistics', to='core.player')),
            ],
            options={
                'db_table': 'player_statistics',
            },
        ),
    ]
